---

- hosts: myhosts #for all hosts 
  become: true 
  pre_tasks: 
  #pre_tasks: this is for if you want to do something before the actual tasks of the playbook .
  - name: installing updates only (Alma)
    dnf:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "AlmaLinux"

    
  - name: installing updates only (Ubuntu)
    ansible.builtin.apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"



- hosts: web_servers 
  become: true
  tasks:
 
  - name: install apache2 and php support packages
    package: 
      name:
        - "{{ apache_package }}"
        - "{{ php_package }}"
      state: latest 
      update_cache: yes

  # Managing service of apache inside alma server
  - name: start httpd (Alma)
    tags: apache,httpd,alma
    service:
      name: httpd
      state: started
    when: ansible_distribution == "AlmaLinux"

  - name: copy default html file for site
    tags: apache,apache2,html
    copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644


  - name: modifying file content on a specific file (Alma)
    tags: apache,httpd,alma
    lineinfile:
      path: /etc/httpd/conf/httpd.conf
      regexp: '^ServerAdmin'
      line: ServerAdmin root@localhost
    when: ansible_distribution == "AlmaLinux"
    register: httpd

  - name: service restarted (AlmaLinux)
    tags: apache,httpd,alma
    service:
      name: httpd
      state: restarted
    when: httpd.changed # it will check if the register* property is changed or not from previous checkpoint after running that module in which it is stated as httpd.

 
