---

- hosts: myhosts #for all hosts 
  become: true 
  pre_tasks: 
  #pre_tasks: this is for if you want to do something before the actual tasks of the playbook .
  - name: Update repository index(Alma)
    dnf:
      # update_only: yes
      update_cache: true
      changed_when: false
    when: ansible_distribution == "AlmaLinux"
  
  - name: installing updates only (Ubuntu)
    ansible.builtin.apt:
      # upgrade: dist
      update_cache: true
      changed_when: false
    when: ansible_distribution == "Ubuntu"

- hosts: all
  become: true
  roles:
    - base    
  
- hosts: web_servers 
  become: true
  roles:
    - web_servers
        
- hosts: db_servers
  become: true
  roles:
    - db_servers
  
